linters:
  enable-all: true

  disable:
    # deprecated
    - execinquery
    - gomnd

    # annoying
    - wsl

linters-settings:
  depguard:
    rules:
      Main:
        allow:
          - calendar-sync/cmd
