name: 'Build image'
description: 'Build the docker image'
inputs:
  image:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tag'
    required: true
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: wistia/parse-tool-versions@v2.1.0
      with:
        filename: '.tool-versions'
        uppercase: 'true'
        suffix: '_tool_version'

    - uses: earthly/actions-setup@v1
      with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build image
      shell: bash
      run: |
        earthly \
          --push \
          +image \
            --image=${{ inputs.image }}:${{ inputs.tag }} \
            --GOLANG_VERSION=${{ env.GOLANG_TOOL_VERSION }}
