# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push temporary image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v2.1.0
        with:
          filename: '.tool-versions'
          uppercase: 'true'

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY }}" }

      - name: Run tests
        shell: bash
        run: |
          earthly \
            +ci \
              --GOLANG_VERSION=${{ env.GOLANG }} \
              --GOLANGCILINT_VERSION=${{ env.GOLANGCI_LINT }} \
              --image=${{ env.FS_IMAGE }}:${{ env.FS_TAG }}
