# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v2.1.0
        with:
          filename: '.tool-versions'
          uppercase: 'true'

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY }}" }

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        shell: bash
        run: |
          earthly \
            --push \
            +release \
              --image=ghcr.io/${{ github.repository }}:latest \
              --GOLANG_VERSION=${{ env.GOLANG }}
